### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by andreasn**
Update to a newer runtime

### CODE REVIEW

**Comment by andreasn** [comment]
This is a work-in-progress. My goal was to update to 3.30, but 3.28 is the highest I've been able to go.

**Comment by andreasn** [comment]
This is the build error I got when I tried to set the runtime to 3.30:
`checking for platform... unix
checking whether to turn on debugging... no
checking whether to turn on profiling... no
checking for JSON... no
configure: WARNING: Could not find 'json-c', trying legacy 'json' instead
checking for JSON... no
configure: error: Package requirements (json) were not met:

Package 'json', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JSON_CFLAGS
and JSON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Error: module libmypaint: Child process exited with code 1

`

**Comment by TingPing** [comment]
So build `json-c`?

**Comment by TingPing** [comment]
bot, build

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Fails with python2: https://flathub.org/builds/#/builders/2/builds/5956

**Comment by barthalion** [comment]
bot, build

**Comment by nedrichards** [comment]
Build is good.

**Pull request merged**
