### PR TITLE
Update GNOME runtime to version 47.

### PR DESCRIPTION
**Pull request by yakushabb**
GNOME runtime version 45 has reached EOL.

### CODE REVIEW

**Comment by yakushabb** [comment]
@bbhtt It's ready for review.

**Comment by hfiguiere** [comment]
really moving to 47 should be the proper course of action.

**Comment by bbhtt** [comment]
Yes, this should target 47 as that is already out for the last 2 months. That gives a larger support period for low maintenance apps.

**Comment by yakushabb** [comment]
Is there any patch that make possible to MyPaint run on runtime 47?

**Comment by bbhtt** [comment]
What's broken on 47? Can you share some error log etc.?

**Comment by yakushabb** [comment]
> What's broken on 47? Can you share some error log etc.?

https://github.com/flathub/org.mypaint.MyPaint/pull/16#issuecomment-2465293574

**Comment by hfiguiere** [comment]
you can try to upgrade json-c. GIMP uses a more recent.

**Comment by yakushabb** [comment]
> you can try to upgrade json-c. GIMP uses a more recent.

Fingers crossed. One more commit for runtime 47.

**Comment by yakushabb** [comment]
> you can try to upgrade json-c. GIMP uses a more recent.

Ready for review.

**Pull request merged**
