### PR TITLE
Update runtime to 47

### PR DESCRIPTION
**Pull request by yakushabb**

### CODE REVIEW

**Comment by yakushabb** [comment]
```
`arraylist.c: In function ‘array_list_new’:
arraylist.c:49:43: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
   49 |   if(!(arr->array = (void**)calloc(sizeof(void*), arr->size))) {
      |                                           ^~~~
arraylist.c:49:43: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors
make[2]: *** [Makefile:587: arraylist.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
json_object.c: In function ‘json_object_new’:
json_object.c:227:50: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
  227 |         jso = (struct json_object*)calloc(sizeof(struct json_object), 1);
      |                                                  ^~~~~~
json_object.c:227:50: note: earlier argument should specify number of elements, later size of each element
cc1: all warnings being treated as errors
make[2]: *** [Makefile:587: json_object.lo] Error 1
make[2]: Leaving directory '/run/build/json-c'
make[1]: *** [Makefile:651: all-recursive] Error 1
make[1]: Leaving directory '/run/build/json-c'
make: *** [Makefile:448: all] Error 2
FB: host_command_exited_cb 1498233 512
]2;flatpak-builder: Cleanup json-cError: module json-c: Child process exited with code 2
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-3/build/.flatpak-builder/rofiles/rofiles-cbz1Me`
```

**Comment by hfiguiere** [comment]
there are patches around for that.

**Comment by yakushabb** [comment]
> there are patches around for that.

Runtime 46 worked fine. 

https://github.com/flathub/org.mypaint.MyPaint/pull/17

**Comment by hfiguiere** [comment]
that's because it uses the same runtime base, which has a less strict gcc that let buggy code go through more easily. It's just delaying things: 46 will be EOL in less than 6 month.

As I said there are patches around on flathub for this problem. The dependency is more popular than it is maintained.

**Pull request closed without merging**
